---
# Handlers for ansible-squid.

- name: restart iptables
  service: name=iptables state=restarted

- name: restart ip6tables
  service: name=ip6tables state=restarted

- name: restart squid
  service: name=squid state=restarted
